version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lantamal-ix
      POSTGRES_DB: spyx
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lantamal-ix
      POSTGRES_DB: spyx
    ports:
      - "6969:5432"

  frontend:
    build:
      context: ./nama-korps
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
